### ISSUE TITLE
search timestamp handling

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/indigo#166]
This is an *old* issue, but assuming it will still be present in `pulumi`.

```
failed to handle op: indexing post: post (41345, app.bsky.feed.post/3jvdilglu7j2n) had invalid timestamp ("2023-05-10T00:05:55.720835Z"): parsing time "2023-05-10T00:05:55.720835Z" as "2006-01-02T15:04:05.000Z": cannot parse "835Z" as "Z"
```

When creating timestamps we have been doing milisecond precision (three digits after "second"), but it seems reasonable to expect `pulumi` to be able to handle longer timestamp precision (at least discarding the extra digits). This is a known ambiguity in the current Lexicon datetime specification.

**Comment by notque** [comment]
time.go has

const ISO8601 = "2006-01-02T15:04:05.000Z"

will it always be at a higher time percision? In which case

`const ISO8601 = "2006-01-02T15:04:05.000000Z"` although i think it's no longer ISO8601 then, and i'm not sure what the format name is.

but it sounds like instead that it's back and forth, in which case

`func parseTimestamp(ts string) (time.Time, error) {
    layouts := []string{
        "2006-01-02T15:04:05.000Z",
        "2006-01-02T15:04:05.000000Z",
        // Add more layouts if necessary...
    }
    
    var parsedTime time.Time
    var err error
    
    for _, layout := range layouts {
        parsedTime, err = time.Parse(layout, ts)
        if err == nil {
            return parsedTime, nil
        }
    }
    
    return time.Time{}, fmt.Errorf("timestamp (%s) did not match any known layouts", ts)
}
`

should sort it out? Calling it in the indexPost func with 

`ts, err := parseTimestamp(rec.CreatedAt)`

I can send a pr, but i'm not sure how exactly you want it to operate here.

**Comment by notque** [comment]
it could also be that since i don't understand the requirements, that dropping digits as you suggested is actually the correct solution.

**Comment by bnewbold** [comment]
this is resolved in the newer `atproto/syntax` package
