### ISSUE TITLE
Missing GraphGetBlocks function

### ISSUE THREAD

**Issue by tehcyx** [bluesky-social/indigo#174]
Looking to use some of the functions via indigo but saw that `GraphGetBlocks` seems to be missing. I would expect that function to use `app.bsky.graph.getBlocks` (https://atproto.com/lexicons/app-bsky-graph#appbskygraphgetblocks) similar as it is done in the `GraphGetMutes` -> https://github.com/bluesky-social/indigo/blob/main/api/bsky/graphgetMutes.go

I saw the `GraphGetMutes` is generated based on the comment in the first line but I'm unsure if the missing function is due to cmd/lexgen not being run recently, but it also seems last changes to https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/graph/getBlocks.json were 3 weeks back, when it was last run. (+/- a day maybe).

**Comment by thepudds** [comment]
See #150 and #173.

**Comment by tehcyx** [comment]
Thanks, I didn't see those when I looked through. Will close this then.

**Comment by thepudds** [comment]
No worries!  I think #173 is the one that will end up getting merged.

FWIW, I’ve been using this commit from my branch in a `replace` directive for the last couple of weeks:

https://github.com/thepudds/indigo/commit/8f0007ca81306dc09e421a69944aa878616edd9f

**Comment by tehcyx** [comment]
I just used a temp workaround: https://github.com/tehcyx/bsky-audit-log/blob/main/tool/main.go#L210-L229
