### ISSUE TITLE
Generated `const` LexiconTypeID is incorrect for `LabelDefs_SelfLabels`

### ISSUE THREAD

**Issue by strideynet** [bluesky-social/indigo#281]
```go
// LabelDefs_SelfLabels is a "selfLabels" in the com.atproto.label.defs schema.
//
// Metadata tags on an atproto record, published by the author within the record.
//
// RECORDTYPE: LabelDefs_SelfLabels
type LabelDefs_SelfLabels struct {
	LexiconTypeID string                 `json:"$type,const=com.atproto.label.defs" cborgen:"$type,const=com.atproto.label.defs"`
	Values        []*LabelDefs_SelfLabel `json:"values" cborgen:"values"`
}
```

See `com.atproto.label.defs` which should be `com.atproto.label.defs#selfLabels`

Fortunately, this doesn't seem affect unmarshalling - meaning that reading data from a well-behaved PDS/BGS is fine. However, it does mean that when trying to use the Go PDS/BGS, the incorrect type ID is being used when marshaling - this is causing my test suites to fail whilst my feed performs fine with live data from the Typescript PDS/BGS. I'm not entirely sure if this affects making posts with self labels from the Go client with the Typescript PDS - this isn't something I've tried.

I've tried looking into `lex/gen.go` to try and resolve this but there's too much to wrap my head around in there.

**Comment by bnewbold** [comment]
I think that this specific issue has been fixed (that line now has `const=com.atproto.label.defs#selfLabels`)
