### ISSUE TITLE
Contributor sign-offs on MIT+Apache2 license extension

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/indigo#403]
We are planning to re-license this repository (`bluesky-social/indigo`) from straight MIT License to "MIT or Apache-2".

The main motivation for this change is to clarify that this source code is free and open in terms of *patents*, in addition to the existing copyright grants from the MIT license. This is an expansion of reuse rights; any downstream user of the source code can continue to use MIT-only if they like. You can read more about this specific license combination at https://protocol.ai/blog/announcing-the-permissive-license-stack/, and see an example atproto project with this license setup at https://github.com/did-method-plc/did-method-plc

I ran through the list of contributors to this repo (https://github.com/bluesky-social/indigo/graphs/contributors), and excluded current Bluesky staff, contributions which were primarily documentation, and some very short contributions.

The remaining contributors are:

- [x] @mattn 
- [x] @jmhodges 
- [x] @erka 
- [x] @bradfitz

If you folks are OK with this license change and can reply to this github issue indicating as such, that would be much appreciated.

If not, that is also fine, and sorry for the noise. We may revert patches or find some other solution.

Either way, thanks again for your contributions!

**Comment by bradfitz** [comment]
Fine by me. I approve relicensing any of my work to MIT or Apache-2.

**Comment by jmhodges** [comment]
Works for me!

**Comment by mattn** [comment]
Yes, I approve relicensing on my changes.

**Comment by erka** [comment]
It works for me too.

**Comment by bnewbold** [comment]
thanks again everybody!
