### ISSUE TITLE
hepa: race condition with `lastSeq` variable

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/indigo#538]
I'm playing fast and loose with a variable (`lastSeq`) in the hepa main process, which is written every time a new event is processed, and read occasionally by a thread which persists "last seen" to redis.

The data race detector doesn't like this. Reasonable!

One improvement would be making access more safe and explicit. Another would be, potentially, tracking this number more correctly in the parallel backfill worker (or some other shared code), which would more correctly track the lowest outstanding partially-processed sequence number; as-is, there are multiple threads processing events, and some threads might be behind.

**Comment by mwat56** [comment]
From what I understand it seems you should look at the _sync/atomic_ functions (or use a _mutex_).

**Comment by bnewbold** [comment]
Indeed! We used atomics for this in https://github.com/bluesky-social/indigo/pull/560

Thanks for the note
