### ISSUE TITLE
My Data (.getRepo files) Not Easy

### ISSUE THREAD

**Issue by Kuroo2021** [bluesky-social/indigo#627]
I'm okay with tech stuff, but I just exported my data to get my following list, after doing so, I found out that the file is a .getRepo file. I can figure out how to extract the data to read it. I'm still trying to figure out how to get my data from the file, and for others, it may be much more complicated as they are not as learned as others. Maybe it would be a better way for the not so-learned to get there data from the file or have repository exports in [this blogpost](https://docs.bsky.app/blog/repo-export).
 to give ways for others to understand how to unarchive/unzip/unrar whatever it is so it can be accessed.

**Comment by ericvolp12** [comment]
The file you get from `getRepo` is called a Carfile, you can use a tool like the Checkout tool in `atproto.tools` [here](https://github.com/ericvolp12/atproto.tools?tab=readme-ov-file#checkout) to unpack your repo into a bunch of JSON files. The file also contains a MST of your repo but the checkout tool ends up dropping that data once it's found all the records in the repo.
