### ISSUE TITLE
backfill: broken for postgresql

### ISSUE THREAD

**Issue by mrd0ll4r** [bluesky-social/indigo#655]
This recent change (https://github.com/bluesky-social/indigo/pull/652/files#diff-059222fb30fa15aa5784cebb59bcf6107a83f88e0d10a8277d85bfbb89c21300R79) broke the backfiller if running on a Postgres db:

```
SELECT repo FROM gorm_db_jobs INDEXED BY enqueued_job_idx WHERE state  = 'enqueued' LIMIT 20000
panic: loading backfill jobs: ERROR: syntax error at or near "BY" (SQLSTATE 42601)
```

I guess postgres doesn't have index hinting.

**Comment by ericvolp12** [comment]
Yeah that's my bad, gonna ship a fix in a little bit that should distinguish between SQLite and non-SQLite
