### ISSUE TITLE
get `GOLOG_LOG_LEVEL` working with `dotenv`

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/indigo#66]
This was an issue with the `atproto` PDS as well, and was resolved by loading the `dotenv` stuff before initializing the logger. Maybe we can re-initialize the logger if a dotenv file is found?

**Comment by erka** [comment]
Hi @bnewbold. 

My idea would be a bit different that you expect. I would like to discuss it before making PR with changes .

I believe `.env` file will be used only in development environment and `make` file be great tool here. 
It maybe sound extreme but I would suggest to move environment variables setup to `Makefile`. It could be done but adding 
```make
ifneq (,$(wildcard ./.env))
    include .env
    export
endif
```
to the top of `Makefile`. 

Making this change will solve the issue with `GOLOG_LOG_LEVEL`,  cleanup the copy and paste code below from each command and allow to remove `godotenv` from the project 

```go
	// only try dotenv if it exists
	if _, err := os.Stat(".env"); err == nil {
		err := godotenv.Load()
		if err != nil {
			log.Fatal("Error loading .env file")
		}
	}
``` 

What do yo think about it?

**Comment by bnewbold** [comment]
I've never tried parsing a `.env` from a Makefile. Does it work? Does it parse the file as Makefile syntax? I'm not sure if that is a problem or not, might be fine.

The Makefile on it's own wouldn't help with things like `go run` or use of fakermaker and gosky CLIs, which I at least run frequently with different args and rely on `.env` for basic auth and config. It is possible to use a separate wrapper command like `dotenv` (`apt get install dotenv` on Debian), or we could have CLI tools load `.env` and service commands not.

It is a bit weird to have the daemon processes look for `.env` on every invocation, but I also don't think it is causing any problems. I think the `GOLOG_LOG_LEVEL` issue is probably a trivial one-line fix, I just haven't gotten around to testing it. So, overall, feel this is low priority.

**Comment by bnewbold** [comment]
I found a nice fix using `import _ "github.com/joho/godotenv/autoload"`, which reduces boilerplate and works at package `init()` time, so it can out-race the logging setup. It does still look for a `.env` always, but i'm going to prefer that fix for now.

**Comment by erka** [comment]
@bnewbold It's the great solution. Please take a look on PR.
