### ISSUE TITLE
Bug on convodefs.go

### ISSUE THREAD

**Issue by xtianpu** [bluesky-social/indigo#692]
There is a bug on here which making failure to decode embed record

https://github.com/bluesky-social/indigo/blob/d5f797ca4b60b665585f73a7b5a61fb534de62b9/api/chat/convodefs.go#L242

Data type should be [EmbedRecord_View](https://github.com/bluesky-social/indigo/blob/d5f797ca4b60b665585f73a7b5a61fb534de62b9/api/bsky/embedrecord.go#L27)

**Comment by bnewbold** [comment]
cc: @whyrusleeping

**Comment by xtianpu** [comment]
solved by https://github.com/bluesky-social/indigo/pull/693 

thank you so much 🙏
