### ISSUE TITLE
PDS<>BGS Sync Megaissue

### ISSUE THREAD

**Issue by whyrusleeping** [bluesky-social/indigo#77]
Making this issue to keep track of any known event stream/sync issues.

- [ ] PDS occasionally sends an event for a repo with an empty car file and a `null` prev field, despite the repo having pre-existing commits
- [ ] BGS occasionally gets into a backfill mode and claims that it has missing blocks.
  - In *most* (but not all) cases, these are encountered when processing the 'next' commit beyond the one currently set as the head in the repo
  - In other cases, the missing blocks are in the middle of the backfilled commit range.
  - It has been observed in some cases (unknown if *all* cases) that the missing blocks occur in multiple places in the commit history for the repo in question

**Comment by whyrusleeping** [comment]
The latter issue is currently being worked around by always sharing the blockstore for the users repo during backfill commit walking (ref: https://github.com/bluesky-social/indigo/blob/main/repomgr/repomgr.go#L1015)
Since deploying that I havent noticed the issue at all, but it feels like the wrong fix

**Comment by snarfed** [comment]
These would be great fodder for any eventual developer FAQ or validator tooling for people building their own PDSes and BGSes!
