### ISSUE TITLE
Scrolling a search while logged out doesn't work due to a 403 error on `app.bsky.feed.searchPosts` requests

### ISSUE THREAD

**Issue by afontenot** [bluesky-social/indigo#797]
I apologize if this isn't the right repository to report this bug against, I'm not really familiar with the different elements.

I was trying to search for something on https://bsky.app while not logged in. I got repeated errors that looked like 

```
We're sorry, but your search could not be completed. Please try again in a few minutes.
Error: Error: NetworkError when attempting to fetch resource.
```

Looking at the browser console, I saw 403 errors on this URL:

    https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts?q=test&limit=25&cursor=25&sort=latest

In fact, just trying to open [the link in a browser](https://public.api.bsky.app/xrpc/app.bsky.feed.searchPosts?q=test&limit=25&cursor=25&sort=latest) shows an error as well. I also see an `OPTIONS` request from the browser which 403s as well, with a response that can't be read due to missing CORS headers.

**Comment by db3000** [comment]
Possibly related to https://github.com/bluesky-social/atproto/issues/2838 , the reverse proxy in front of the public bluesky api is configured to reject `app.bsky.feed.searchPosts` requests with the `cursor` parameter specified due to load issues.

**Comment by afontenot** [comment]
@db3000 I think that's definitely the same issue! I'll close this since there's already engagement on the other issue.

If Bluesky devs feel it's more appropriate for this repo, they can reopen.
