### ISSUE TITLE
remove source PDS login from `goat account migrate`?

### ISSUE THREAD

**Issue by snarfed** [bluesky-social/indigo#799]
Hey @bnewbold! `goat` is awesome, again, thank you so much for making it!

I'm curious about the need for logging into the source PDS. Are there any methods you need to call on it that are authed? The "manual" approach you describe in https://whtwnd.com/bnewbold.net/3l5ii332pf32u#:~:text=Manual%20Account%20Migration doesn't need auth. Or is it to add friction to using this to clone other people's accounts?

I ask because some Bridgy Fed users are interested in trying to migrate their bridged accounts out, but BF obviously doesn't support login. It'd be great if they could try it with `goat` more easily. https://github.com/snarfed/bridgy-fed/issues/1137

**Comment by Tamschi** [comment]
`goat` probably has to get a service auth token from the source PDS.

(Manually migrating off Bridgy Fed is blocked at least on that too I think.)

**Comment by snarfed** [comment]
Sure, but I don't know what it needs that auth token for. You can download an entire repo via `getRepo` without auth.

**Comment by snarfed** [comment]
Oh, it's probably for deactivating the old account. If so, I guess this is a feature request to make that optional, and not require auth if it's skipped.

**Comment by Tamschi** [comment]
Oh, I was mistaken. What's needed and not supported by Bridgy Fed is this step:

> If using a PDS-managed `did:plc`, you can edit the parameters to match any additional services or recovery keys. Save the results as `./plc_unsigned.json`. You will need to request a PLC signing token from the PDS:
>
> ```bash
> # old PDS
> goat account plc request-token
> ```
>
> Retrieve the token ($PLCTOKEN) from email, then request a signed version of the PLC params:
>
> ```bash
> # old PDS
> goat account plc sign --token $PLCTOKEN  ./plc_unsigned.json > plc_signed.json
> ```

Or more precisely a way to sign that data to switch `did:plc` ownership. Bridgy Fed should likely also listen to that ownership change to stop processing the account, though that's somewhat optional since after this PLC operation is submitted to the new PDS and published, anything further will be rejected by the network.

**Comment by snarfed** [comment]
Ah, good point! True, in practice right now,  the source PDS (here BF) usually owns the recovery and signing keys, so for migrations where you preserve the DID, which ideally should be the norm, the source PDS would need to help update the DID doc.

Theoretically, the way the protocol was designed, ideally the user should hold the recovery key(s), not the PDS. That makes recoverability difficult though, and also takes nontrivial UX to do well, so I definitely understand why they haven't prioritized it.

OK, never mind, I get the need for auth now. Closing!
